### ISSUE TITLE
[BUG] Modulorails try to update the rubocop file for each rails command

### ISSUE THREAD

**Issue by DalfDev** [moduloTech/modulorails#18]
![Capture d’écran 2022-02-23 à 10 52 32](https://user-images.githubusercontent.com/22856557/155296180-eb7ec728-e5d0-41fe-a46d-ac766d915ff0.png)

**Comment by winnieoursbrun** [comment]
Not sure it's a bug, but more a feature. rubocop file is overridden to ride over manual changes.

**Comment by Ezveus** [comment]
It's working as intended.
